### ISSUE TITLE
Using an environment variable for the API key doesn't work

### ISSUE THREAD

**Issue by MoritzLost** [convergine/craft-brevo#1]
Using an environment variable for the API key doesn't work.

To reproduce:

1. Add this to your `.env`:

```
BREVO_API_KEY="your-key-here"
```

2. In the email settings, set **Transport Type** to **Brevo** and **API Key** to `$BREVO_API_KEY` (the field indicates that this is supported).
3. Try to send an e-mail: `php craft mailer/test --to=your-email@example.com`. This will fail with HTTP 401 and message "Key not found" returned by the API.

The reason is that the plugin doesn't actually parse the environment variable, so it literally uses `$BREVO_API_KEY` as the API key.

**Comment by MoritzLost** [comment]
I've created a pull request to fix this (oops, wrong repo): https://github.com/convergine/craft-brevo/pull/2

**Comment by convergine** [comment]
Thank you for your contribution @MoritzLost !
